# Generated by Django 6.0.3 on 2026-03-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesamount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saledate', models.DateTimeField(null=True)),
            ],
        ),
    ]
