# Generated by Django 5.2.12 on 2026-03-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesamount', models.DecimalField(db_default=0.0, decimal_places=2, max_digits=10)),
                ('salesdate', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'sales',
            },
        ),
    ]
