# Generated by Django 5.2.12 on 2026-03-18 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prouduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50)),
                ('descriptions', models.CharField(max_length=100, unique=True)),
                ('qty', models.IntegerField(db_default=0)),
                ('unit', models.CharField(blank=True, max_length=10)),
                ('costprice', models.DecimalField(db_default=0.0, decimal_places=2, max_digits=10)),
                ('sellprice', models.DecimalField(db_default=0.0, decimal_places=2, max_digits=10)),
                ('saleprice', models.DecimalField(db_default=0.0, decimal_places=2, max_digits=10)),
                ('productpicture', models.TextField(blank=True, max_length=215, null=True)),
                ('alertstocks', models.IntegerField(db_default=0)),
                ('criticalstocks', models.IntegerField(db_default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_rel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.categories')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
